# Generated by Django 3.0.3 on 2021-05-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning_poker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=200, verbose_name='API Url')),
                ('username', models.CharField(max_length=200, verbose_name='API Username')),
                ('story_points_field', models.CharField(max_length=200, verbose_name='Story Points Field')),
            ],
            options={
                'verbose_name': 'Jira Connection',
                'verbose_name_plural': 'Jira Connections',
            },
        ),
        migrations.CreateModel(
            name='JiraStory',
            fields=[
                ('story_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planning_poker.Story')),
                ('jira_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning_poker_jira.JiraConnection')),
            ],
            options={
                'verbose_name': 'Jira Story',
                'verbose_name_plural': 'Jira Stories',
            },
            bases=('planning_poker.story',),
        ),
    ]
