# Generated by Django 3.0.3 on 2021-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0001_initial'),
        ('planning_poker_jira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconnection',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Label'),
        ),
        migrations.DeleteModel(
            name='JiraStory',
        ),
    ]
