# Generated by Django 3.0.3 on 2021-05-18 10:19

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker_jira', '0002_added_a_label_to_jiraconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconnection',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='jiraconnection',
            name='api_url',
            field=models.CharField(max_length=200, verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='jiraconnection',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='API Username'),
        ),
    ]
